### ISSUE TITLE
parser_fulaf_api: Test issue

### ISSUE THREAD

**Issue by olafurrognvaldsson** [hackerott/TOK#1]
Testing if I can create an issue regarding the parser

**Comment by hackerott** [comment]
@beneduzi , 

Can you recheck the code in the part that reads the netcdf and look for rain?

It is this one, right? https://github.com/hackerott/TOK/blob/master/parser_fulaf_api/source/parser_wrf.py

**Comment by olafurrognvaldsson** [comment]
This is very suspicious, according to the scatteogram most of the stations have no precipitation in the model
![screen shot 2017-07-10 at 17 42 55](https://user-images.githubusercontent.com/18738411/28026778-61bf1f66-6597-11e7-88ea-eb7489db857f.png)
But if we look at the 24hr precip (plotted using `panoply`) we see a different picture (sorry about the plot, but we can see the outlines of SW-Norway between x=50.7 and x=101.9)
![screen shot 2017-07-10 at 17 44 45](https://user-images.githubusercontent.com/18738411/28026833-7fca68b2-6597-11e7-9d6e-9a9854b1b341.png)
Changing the color scheme so that precip>1mm is read gives us this
![screen shot 2017-07-10 at 17 46 37](https://user-images.githubusercontent.com/18738411/28026918-bf84cf1a-6597-11e7-969a-bb635e385afc.png)
If the majority of model points would have zero precip, this plot should be more or less "blue" and not "red"

**Comment by olafurrognvaldsson** [comment]
This shows accumulated 24hr precipitation at 2014-10-25_06, simulated at 4km resolution

**Comment by hackerott** [comment]
It seems a problem with date. 
We tested the code for day 22. @beneduzi , How is the sintaxe to take rain from 2014-10-24_06 to 2014-10-25_06

**Comment by olafurrognvaldsson** [comment]
I'm going to create proper plots of the accumulated precipitation in python so we can better compare them to the values shown by the parser code

**Comment by olafurrognvaldsson** [comment]
The command I gave was: 
`python ./source/main.py ~or/GFI/eklima/obs/24hrprecip-201410.txt ~or/GFI/wrf/2014-10-24/WRF/cntrl/4km/hourly/rav2-4km.nc4  ~or/GFI/met-api/stationlist.csv ./ 2014102406 2014102506 True`
The input files are available here: ftp://ftp.betravedur.is/pub/wrf/gfi/ (@beneduzi, note that the wrfout file has been modified since this morning)

**Comment by hackerott** [comment]
The command is right. The code should creat the WRF rain field  that it read.

**Comment by hackerott** [comment]
model_simulation.png
Check this one. Should be equal to the one from ncview

**Comment by olafurrognvaldsson** [comment]
@hackerott the file is missing :)

**Comment by hackerott** [comment]
We should enable in the main. I'm checking how

**Comment by olafurrognvaldsson** [comment]
I've just run the code with the `False` key. I now get 410 files under the `2014102506` directory, and they all look something like this:
```
Olafurs-MacBook-Air:2014102506 or$ cat 2014102506_7420.csv
7420
 date; WRF; Station

Olafurs-MacBook-Air:2014102506 or$
```
Does this look right???

**Comment by hackerott** [comment]
It should have the date and accumulated precipitation measured by both model and station

**Comment by olafurrognvaldsson** [comment]
This just gets stranger, with the `False` key set we get a completely different scatterogram
![screen shot 2017-07-10 at 20 17 55](https://user-images.githubusercontent.com/18738411/28033059-fda213c4-65ac-11e7-81c6-0489d0f5cc88.png)

**Comment by olafurrognvaldsson** [comment]
OK, so there is clearly something wrong going on

**Comment by hackerott** [comment]
We will check. This may take sometime to find out the problem. Me and Gustavo will work on this today and tomorrow.

**Comment by olafurrognvaldsson** [comment]
OK cool

**Comment by olafurrognvaldsson** [comment]
This is how the 24 hour accumulated precipitation pattern looks like (valid at 2014-10-25_06)
![map](https://user-images.githubusercontent.com/18738411/28065135-98ec4734-6637-11e7-88a0-f943b1c3cbfe.png)
Unfortunately we don't have observations from Sweden to see if the modelled maxima, just south of the Swedish boarders, is in the correct location. Or, if there is a shift to the south.

**Comment by olafurrognvaldsson** [comment]
This is an updated figure where I've changed the colour scale so that <1mm precipitation is shown as white/clear (the threshold was at 0.1mm in the figure above)
![map](https://user-images.githubusercontent.com/18738411/28067589-28bff8b0-6642-11e7-946d-c43184c92770.png)
It can be seen that the only area in Norway where the 24hr precipitation is less than 1mm is between 10° and 12° E and around 63° N

**Comment by olafurrognvaldsson** [comment]
@hackerott  and @beneduzi there is still an error in how the code is reading the values from the WRF file. Here is an example of accumulated precipitation from station #18162, the 24hr accumulated precipitation is circa 4.3mm but according to the `2014102506_18162.csv` file it is 0.0099...
![timeseries_accum](https://user-images.githubusercontent.com/18738411/28075264-44b68c64-665b-11e7-852d-03f369027e86.png)

**Comment by olafurrognvaldsson** [comment]
Three comments on the `csv` files:
1) The order in the header says `date; WRF; Station`, but what is written is `date; Station; WRF`
2) We should limit the number of digits to one
3) The date-format doesn't look right `[datetime.datetime(2014, 10, 25, 6, 0)]; [7.2000000000000002]; [0.0099999999999980105]`, i.e. it looks like it is not returning the value of the `datetime.datetime` function

**Comment by beneduzi** [comment]
Actualy its return the object datetime, without any kinf of formating
I didnt limited the decimal values to get a more acured result, it could be done very easy 
I will commit this changes later today, and I will check again the data aquisition.

**Comment by olafurrognvaldsson** [comment]
There is something seriously wrong with the code. When I try and run the November case the code just hangs. I've uploaded the observational file here:
ftp://ftp.betravedur.is/pub/wrf/gfi/24hrprecip-201411.txt

**Comment by olafurrognvaldsson** [comment]
@hackerott @beneduzi there is an error in `parser_wrf.py`. There is no need to loop through the RAINNC values. Rather, you should take the difference between `RAINNC[date1]` and `RAINNC[date0]`. This is the value we are looking for, i.e. the accumulated precipitation between time=time0 and time=time1

**Comment by olafurrognvaldsson** [comment]
I'm uploading the python code that I used to create the last figure. I think the `def workWRFDates(times):` routine might proof useful.
[plotExPrecFlood.txt](https://github.com/hackerott/TOK/files/1139947/plotExPrecFlood.txt)

**Comment by olafurrognvaldsson** [comment]
@hackerott @beneduzi I have re-arranged the data on our ftp-server. Observations can now be found here:
ftp://ftp.betravedur.is/pub/wrf/gfi/observations/
and the wrfout-files are located, depending on resolution, under
ftp://ftp.betravedur.is/pub/wrf/gfi/wrf-2km/
ftp://ftp.betravedur.is/pub/wrf/gfi/wrf-4km/
ftp://ftp.betravedur.is/pub/wrf/gfi/wrf-12km/
Note that, at the moment, only `wrf-4km` has all cases

**Comment by hackerott** [comment]
@olafurrognvaldsson . We (specially Gustavo) worked on the code today,but we haven't find anything wrong. The code was modified to your suggestion to read only the fist and last time in the 24h instead of adding every 1h step. But no changes...
We are now preparing a shaded plot of WRF precipitation from the parser to compare with the ncview output.

**Comment by olafurrognvaldsson** [comment]
@hackerott @beneduzi I noticed an error in lines 23 to 25 in `parser_wrf.py`
```
time_delta = date_f - date_i 
max_i = time_delta.days // 24
out = WRF_rain_ncu[max_i, ix, iy] - WRF_rain_ncu[0, ix, iy]
```
here `out` should simply be:
```
out = WRF_rain_ncu[date_f,ix,iy] - WRF_rain_ncu[date_i,ix,iy]
```
i.e. simply the difference between RAINNC(final-time) and RAINNC(initial-time) where the `initial-time` and `final-time` are provided as command line input to the program.

The way the code is written now, `max_i` is probably equal to 1 so what you are computing is basically the accumulated precipitation between the zeroth and first time step in the file.

**Comment by olafurrognvaldsson** [comment]
@hackerott @beneduzi I'm looking at lines 26 and 27 of the latest version of `parse_wrf.py` 
```
	max_i = time_delta.days * 24
	out = WRF_rain_ncu[max_i, ix, iy] - WRF_rain_ncu[0, ix, iy]
```
(at 13:23 UTC) and it is clear you are thinking this wrong. The code needs to be able to sum up accumulated precipitation over an arbitrary time period, NOT necessarily over a fixed chunks of 24-hour periods. Also, `time zero = date_i` is not = 0 (i.e. the initial time step of the file).

**Comment by olafurrognvaldsson** [comment]
@hackerott @beneduzi I just realised that some of the wrfout-files end prematurely, i.e. they end at 05:00 UTC, and not 06:00 UTC. This does not affect the model results, but it will wreak havoc with the current version of the parser-code.
I propose we solve this by having optionally two sets of of initial- and end-dates. One set would cover the initial- and end-dates of the observations. The other set would describe the initial- and end-dates of the wrf simulation. 
In 99% of the time these would be identical, but in few cases the end hour of the wrf-simulation would be `05` and not `06`
Please note that the initial- and end-times do NOT have to be the same as the initial- and end-time of the wrfout-files!!!

**Comment by olafurrognvaldsson** [comment]
@beneduzi @hackerott  the simplest way to get the correct index number for the RAINNC variable would be like this 
```
## Calculate dates
logging.info('Converting times-array to datetime')
dates = workWRFDates(times[:])
print 'dates are: ', dates[0]
begin=dates[0] #this is just an example, in our case this would be `date0`
end=dates[-1] #this is just an example, in our case this would be `date1`
begin_index=numpy.where(dates==begin)
## need to convert the tuple into integer
begin_index=int(begin_index[0])
end_index=numpy.where(dates==end)
## need to convert the tuple into integer
end_index=int(end_index[0])
```
This way, we have successfully converted the begin- and end-dates to the correct indices for the wrfout-variables.

**Comment by olafurrognvaldsson** [comment]
@beneduzi can you run this command?
```
python ./source/main.py ~or/GFI/eklima/obs/24hrprecip-201411.txt ~or/GFI/wrf/2014-11-24/WRF/cntrl/4km/hourly/rav2-4km-wrfout_d01_2014-11-22_00_surface_reduced.nc4 ~or/GFI/met-api/stationlist.csv ./results/2014-11-24/ 2014112406 2014112506 False
```
The code either hangs or returns this type of error:
```
...........................................................................
/Users/or/GFI/TOK/parser_fulaf_api/source/parser_station.py in DATA_get(station_file='/Users/or/GFI/eklima/obs/24hrprecip-201411.txt', station='100', path2='/Users/or/GFI/wrf/2014-11-24/WRF/cntrl/4km/hourl...-4km-wrfout_d01_2014-11-22_00_surface_reduced.nc4', path3='/Users/or/GFI/met-api/stationlist.csv', date1='2014112506')
      9 import lat_lon
     10 
     11 ################################################################################
     12 ##Creates the array with all data and dates from station files 
     13 def DATA_get(station_file, station, path2, path3, date1):
---> 14 	raw_data = np.genfromtxt(station_file, delimiter=";",skip_header=500, skip_footer=11)
        raw_data = undefined
        station_file = '/Users/or/GFI/eklima/obs/24hrprecip-201411.txt'
     15 	date1 = datetime.datetime.strptime(str(date1), '%Y%m%d%H')
     16 	station_self	= raw_data[:,0]
     17 	year		= raw_data[:,1]
     18 	month		= raw_data[:,2]

...........................................................................
/Users/or/anaconda/lib/python2.7/site-packages/numpy/lib/npyio.py in genfromtxt(fname='/Users/or/GFI/eklima/obs/24hrprecip-201411.txt', dtype=dtype('float64'), comments='#', delimiter=';', skip_header=500, skip_footer=11, converters=[<numpy.lib._iotools.StringConverter object>], missing_values=[['']], filling_values=[None], usecols=None, names=None, excludelist=None, deletechars=None, replace_space='_', autostrip=False, case_sensitive=True, defaultfmt='f%i', unpack=None, usemask=False, loose=True, invalid_raise=True, max_rows=None)
   1761         if len(errmsg):
   1762             errmsg.insert(0, "Some errors were detected !")
   1763             errmsg = "\n".join(errmsg)
   1764             # Raise an exception ?
   1765             if invalid_raise:
-> 1766                 raise ValueError(errmsg)
        errmsg = 'Some errors were detected !\n    Line #511 (got 7...f 1)\n    Line #14493 (got 7 columns instead of 1)'
   1767             # Issue a warning ?
   1768             else:
   1769                 warnings.warn(errmsg, ConversionWarning)
   1770 

ValueError: Some errors were detected !
    Line #511 (got 7 columns instead of 1)
    Line #512 (got 7 columns instead of 1)
:
:
:
```
